"""Write the latest calibration into the Arduino sketches.

    python calibration/apply.py                    # latest run in calibration/data/
    python calibration/apply.py --run 20261009_104859

Reads <run>_constants.txt saved by calibrate.py and writes calibration_values.h
into each sketch folder below. The sketches #include it, so re-upload them after
running this. calibrate.py runs this automatically at the end of a calibration.

FOUND_THRESHOLD is not applied: the suggestion only measures sensor noise with a
still LED, so it is recorded in the header as CAL_SUGGESTED_FOUND_THRESHOLD and
FOUND_THRESHOLD stays a hand-set value in tracking_mechanism.ino.
"""

import argparse
import re
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"
REPO = Path(__file__).resolve().parent.parent
SKETCH_DIRS = [REPO / "tracking_mechanism", REPO / "tests" / "mechanism_test"]
DEFAULT_MIN_BRIGHTNESS = 200   # used if the run skipped the far step

NUMBER = r"(-?\d+(?:\.\d+)?)"


def latest_run():
    stamps = sorted(p.name.removesuffix("_constants.txt") for p in DATA_DIR.glob("*_constants.txt"))
    if not stamps:
        sys.exit(f"No calibration results in {DATA_DIR}. Run calibrate.py first.")
    return stamps[-1]


def read_constants(stamp):
    path = DATA_DIR / f"{stamp}_constants.txt"
    if not path.exists():
        sys.exit(f"{path} not found.")
    text = path.read_text()
    values = {}
    for name in ["OFF_TL", "OFF_TR", "OFF_BL", "OFF_BR", "GAIN_TL", "GAIN_TR", "GAIN_BL", "GAIN_BR"]:
        m = re.search(rf"\b{name}\s*=\s*{NUMBER}", text)
        if not m:
            sys.exit(f"{name} missing from {path}")
        values[name] = float(m.group(1))
    for name in ["MIN_BRIGHTNESS", "FOUND_THRESHOLD"]:
        m = re.search(rf"suggested {name}\s*=\s*{NUMBER}", text)
        values[name] = float(m.group(1)) if m else None
    return values


def header(stamp, v):
    min_brightness = v["MIN_BRIGHTNESS"]
    if min_brightness is None:
        min_brightness_line = (f"const int MIN_BRIGHTNESS = {DEFAULT_MIN_BRIGHTNESS};"
                               f"   // default: this run skipped the far step")
    else:
        min_brightness_line = f"const int MIN_BRIGHTNESS = {round(min_brightness)};"
    threshold = v["FOUND_THRESHOLD"]
    lines = [
        "// Generated by calibration/apply.py from calibration run " + stamp + ". Do not edit by hand:",
        "// rerun calibrate.py (or apply.py) instead. Calibrated reading = (raw - OFF) * GAIN.",
        "#pragma once",
        "",
        f"const float OFF_TL = {v['OFF_TL']:.1f}, OFF_TR = {v['OFF_TR']:.1f}, "
        f"OFF_BL = {v['OFF_BL']:.1f}, OFF_BR = {v['OFF_BR']:.1f};",
        f"const float GAIN_TL = {v['GAIN_TL']:.3f}, GAIN_TR = {v['GAIN_TR']:.3f}, "
        f"GAIN_BL = {v['GAIN_BL']:.3f}, GAIN_BR = {v['GAIN_BR']:.3f};",
        "",
        "// minimum summed calibrated reading of all 4 sensors to count as seeing the LED",
        min_brightness_line,
        "",
        "// sensor noise with a still, centered LED; not applied, FOUND_THRESHOLD is set by hand",
        f"const float CAL_SUGGESTED_FOUND_THRESHOLD = {threshold if threshold is not None else 0:.4f};",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run", help="run timestamp, e.g. 20261009_104859 (default: latest)")
    args = parser.parse_args()
    apply(args.run or latest_run())


def apply(stamp):
    text = header(stamp, read_constants(stamp))
    for folder in SKETCH_DIRS:
        path = folder / "calibration_values.h"
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO)} from run {stamp}")
    print("Re-upload tracking_mechanism.ino (and mechanism_test.ino) to use the new values.")


if __name__ == "__main__":
    main()
