// Generated by calibration/apply.py from calibration run 20261009_113642. Do not edit by hand:
// rerun calibrate.py (or apply.py) instead. Calibrated reading = (raw - OFF) * GAIN.
#pragma once

const float OFF_TL = 7.0, OFF_TR = 30.0, OFF_BL = 16.8, OFF_BR = 9.7;
const float GAIN_TL = 1.052, GAIN_TR = 0.929, GAIN_BL = 0.970, GAIN_BR = 1.061;

// minimum summed calibrated reading of all 4 sensors to count as seeing the LED
const int MIN_BRIGHTNESS = 188;

// sensor noise with a still, centered LED; not applied, FOUND_THRESHOLD is set by hand
const float CAL_SUGGESTED_FOUND_THRESHOLD = 0.0019;
